# AI Assistant
----------------------------
오더 정보를 입력받아 AI를 통해 해당 오더에 대한 분석 결과를 제공
  1. 오류 유형을 판별하는 것이기 때문에 분류 유형 
  2. 분류 문제에서느 어떤 것을 사용해야 할까?
  3. 가정검사
     * 이상징후 탐지 과제로도 AI사용하는 것 검토 필요
  4. 데이터 작업
      1. 데이터 분석
      - info, describe, value_counts를 통해 데이터 구조 확인

In [1]:
import os
import urllib
import tarfile

DOWNLOAD_ROOT = 'https://raw.githubusercontent.com/ageron/handson-ml2/master/'
HOUSING_PATH = os.path.join("datasets", "housing")
HOUSING_URL = DOWNLOAD_ROOT + "datasets/housing/housing.tgz"

def housing_data(housing_url = HOUSING_URL, housing_path = HOUSING_PATH):
    os.makedirs(housing_path, exist_ok = True)
    tgz_path = os.path.join(housing_path, "housing.tgz")
    urllib.request.urlretrieve(housing_url, tgz_path)
    housing_tgz = tarfile.open(tgz_path)

    housing_tgz.extractall(path=housing_path)
    housing_tgz.close()

In [2]:
housing_data()

In [3]:
import pandas as pd

def load_housing_data(housing_path=HOUSING_PATH):
    csv_path = os.path.join(housing_path, "housing.csv")
    return pd.read_csv(csv_path)

In [4]:
housing = load_housing_data()

In [5]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null float64
total_rooms           20640 non-null float64
total_bedrooms        20433 non-null float64
population            20640 non-null float64
households            20640 non-null float64
median_income         20640 non-null float64
median_house_value    20640 non-null float64
ocean_proximity       20640 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [6]:
housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

### SOMF Data

In [7]:
# data_path = 'D:/07_NeoTransformation/777_Workspace/77_Python_Workspace/777_Project/AI_Assitant/Data/SIT/ai_somf_sit_202006241.csv'
# os.listdir('D:/07_NeoTransformation/777_Workspace/77_Python_Workspace/777_Project/AI_Assitant/Data/SIT')

data = pd.read_csv('./Data/SIT/ai_data_somf_20200622.csv')
data.fillna('0_0_0', inplace=True)
data.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (5,14,15,16,19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ORDERNUMBER,ORDER_SEQ_ID,ORRE,PRDI,LORD,PHRD,RECO,WODI,REAC,JUJO,...,SWBO,MAUP,IDMS,MEIN,CEMS,MCID,DELS,VOIP,ORCN,FUCF
0,15021D506290191,72464887,0_0_0,1_ProvisioningDelayReceiver_R_WaitingForResponse,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,...,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0
1,15070F508129491,87892733,0_0_0,0_0_0,0_0_0,0_0_0,1_FacilityConfirmationReceiver_D_WaitingForRes...,1_WorkforceJobReceiver_D_WaitingForResponse,0_0_0,0_0_0,...,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0
2,15166B010226590,121000924,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,1_WorkforceJobReceiver_D_WaitingForResponse,0_0_0,0_0_0,...,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0
3,15199A504769590,133193503,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,1_WorkforceJobReceiver_D_WaitingForResponse,0_0_0,0_0_0,...,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0
4,152945102160390,162295278,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,1_ResourceActivationReceiver_D_WaitingForResponse,0_0_0,...,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0,0_0_0

In [17]:
data.describe()
data = data.iloc[:1000, :6]

In [20]:
grouped = data[['ORDERNUMBER','ORDER_SEQ_ID','ORRE','PRDI']].groupby(['ORRE', 'PRDI'])
for name, group in data[['ORDERNUMBER','ORRE']].groupby(data['ORRE']):
    print('this is the print of data {} and {}'.format(name, group))

this is the print of data 0_0_0 and          ORDERNUMBER   ORRE
0    15021D506290191  0_0_0
1    15070F508129491  0_0_0
2    15166B010226590  0_0_0
3    15199A504769590  0_0_0
4    152945102160390  0_0_0
..               ...    ...
995  20002C5015062A1  0_0_0
996  20002E5808174AN  0_0_0
997  20003DT1705089N  0_0_0
998  20003EF02338991  0_0_0
999  20003CY017353A1  0_0_0

[999 rows x 2 columns]
this is the print of data 1_PublishServiceOrderSender_U_accepted and          ORDERNUMBER                                    ORRE
250  191024B2818599N  1_PublishServiceOrderSender_U_accepted

In [22]:
grouped.agg(['mean','std', 'max'])

                                                                                         ORDER_SEQ_ID  \
                                                                                                 mean
ORRE                                   PRDI
0_0_0                                  0_0_0                                             5.091983e+08
                                       1_ProvisioningDelayReceiver_R_WaitingForResponse  5.375413e+08
1_PublishServiceOrderSender_U_accepted 0_0_0                                             5.096473e+08

                                                                                                       \
                                                                                                  std
ORRE                                   PRDI
0_0_0                                  0_0_0                                             8.058512e+07
                                       1_ProvisioningDelayReceiver_R_WaitingForResponse  5.571732e+07
1_PublishServiceOrderSender_U_accepted 0_0_0                                                      NaN


                                                                                               max
ORRE                                   PRDI
0_0_0                                  0_0_0                                             572594267
                                       1_ProvisioningDelayReceiver_R_WaitingForResponse  572635824
1_PublishServiceOrderSender_U_accepted 0_0_0                                             509647318

In [33]:
import os
from dateutil.parser import parse

os.listdir('D:/07_NeoTransformation/777_Workspace/77_Python_Workspace/777_Project/AI_Assitant/Data/SIT')

['ai_data_pa_20200622.csv',
 'ai_data_pa_5q_20200622.csv',
 'ai_data_somf_20200622.csv',
 'ai_data_somf_accept_20200622.csv',
 'ai_data_somf_received_20200622.csv']

In [91]:
pna_data = pd.read_csv('D:/07_NeoTransformation/777_Workspace/77_Python_Workspace/777_Project/AI_Assitant/Data/SIT/ai_data_pa_20200622.csv')

In [101]:
pna_data.head()
pna_data_sample = pna_data[:1000].copy()
pna_data_sample['dates'] = ''

pna_data_sample.columns

Index(['CUST_ORDR_NO', 'ORDR_TYPE_ID', 'MAX(POD.PROD_ID)',
       'MAX(POD.FIRST_CRET_DT)', 'MAX(POD.LAST_CHG_DT)',
       'MAX(POD.CUST_ORDR_VER_NO)', 'ORRE', 'PRDI', 'LORD', 'PHRD', 'RECO',
       'WODI', 'REAC', 'JUJO', 'SWBO', 'FUCO', 'MAUP', 'ORCN', 'dates'],
      dtype='object')

In [102]:
columns = pna_data.columns
for i, j in enumerate(columns):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17

In [103]:
for i, j in enumerate(pna_data_sample['MAX(POD.FIRST_CRET_DT)']):
    pna_data_sample.iloc[i, 18] = parse(j)
    print(pna_data_sample.iloc[i, 18])

2023-12-17 00:00:00
2018-06-20 00:00:00
2012-06-14 00:00:00
2011-06-14 00:00:00
2015-06-20 00:00:00
2026-06-14 00:00:00
2025-08-14 00:00:00
2025-08-14 00:00:00
2023-02-15 00:00:00
2001-09-14 00:00:00
2017-09-14 00:00:00
2017-09-14 00:00:00
2019-11-14 00:00:00
2008-12-14 00:00:00
2021-01-15 00:00:00
2023-01-15 00:00:00
2016-02-15 00:00:00
2011-03-15 00:00:00
2008-04-15 00:00:00
2011-05-15 00:00:00
2011-05-15 00:00:00
2004-12-19 00:00:00
2018-07-15 00:00:00
2022-06-20 00:00:00
2026-08-15 00:00:00
2027-08-15 00:00:00
2027-08-15 00:00:00
2019-06-20 00:00:00
2019-06-20 00:00:00
2028-10-15 00:00:00
2023-11-15 00:00:00
2003-12-15 00:00:00
2018-01-16 00:00:00
2017-02-16 00:00:00
2018-02-16 00:00:00
2018-02-16 00:00:00
2018-02-16 00:00:00
2018-02-16 00:00:00
2018-02-16 00:00:00
2018-02-16 00:00:00
2018-02-16 00:00:00
2008-03-16 00:00:00
2017-05-16 00:00:00
2017-05-16 00:00:00
2019-05-16 00:00:00
2026-05-16 00:00:00
2003-06-16 00:00:00
2008-11-18 00:00:00
2011-06-20 00:00:00
2011-06-20 00:00:00
2011-06-20 00:00:00
2004-05-17 00:00:00
2029-08-16 00:00:00
2001-09-16 00:00:00
2007-09-16 00:00:00
2018-06-20 00:00:00
2012-10-16 00:00:00
2005-12-16 00:00:00
2022-06-20 00:00:00
2021-01-17 00:00:00
2024-01-17 00:00:00
2027-02-17 00:00:00
2027-02-17 00:00:00
2013-02-17 00:00:00
2027-02-17 00:00:00
2027-02-17 00:00:00
2027-02-17 00:00:00
2027-02-17 00:00:00
2017-06-20 00:00:00
2014-02-17 00:00:00
2019-06-20 00:00:00
2019-06-20 00:00:00
2031-03-17 00:00:00
2031-03-17 00:00:00
2031-03-17 00:00:00
2031-03-17 00:00:00
2013-04-17 00:00:00
2023-05-17 00:00:00
2019-06-17 00:00:00
2026-06-17 00:00:00
2019-07-17 00:00:00
2021-07-17 00:00:00
2028-01-20 00:00:00
2021-07-17 00:00:00
2021-07-17 00:00:00
2001-12-18 00:00:00
2021-07-17 00:00:00
2021-07-17 00:00:00
2021-07-17 00:00:00
2021-07-17 00:00:00
2026-07-17 00:00:00
2001-08-17 00:00:00
2007-08-17 00:00:00
2018-06-20 00:00:00
2019-09-17 00:00:00
2018-10-17 00:00:00
2030-10-17 00:00:00
2031-10-17 00:00:00
2022-06-20 00:00:00
2015-11-17 00:00:00
2009-11-18 00:00:00
2024-11-17 00:00:00
2027-12-17 00:00:00
2029-11-17 00:00:00
2015-12-17 00:00:00
2028-12-17 00:00:00
2028-12-17 00:00:00
2028-12-17 00:00:00
2017-06-20 00:00:00
2015-01-18 00:00:00
2015-01-18 00:00:00
2025-01-18 00:00:00
2029-01-18 00:00:00
2005-02-18 00:00:00
2005-02-18 00:00:00
2005-02-18 00:00:00
2005-02-18 00:00:00
2013-02-18 00:00:00
2014-02-18 00:00:00
2019-02-18 00:00:00
2020-02-18 00:00:00
2020-02-18 00:00:00
2020-02-18 00:00:00
2012-06-20 00:00:00
2022-06-20 00:00:00
2016-03-18 00:00:00
2028-03-18 00:00:00
2018-06-20 00:00:00
2030-03-18 00:00:00
2030-03-18 00:00:00
2030-03-18 00:00:00
2030-03-18 00:00:00
2009-04-18 00:00:00
2013-05-20 00:00:00
2011-06-20 00:00:00
2009-05-18 00:00:00
2009-05-18 00:00:00
2018-06-20 00:00:00
2004-06-18 00:00:00
2019-06-20 00:00:00
2005-06-18 00:00:00
2007-06-18 00:00:00
2011-06-18 00:00:00
2015-06-18 00:00:00
2022-06-18 00:00:00
2022-06-18 00:00:00
2022-06-18 00:00:00
2029-06-18 00:00:00
2022-06-20 00:00:00
2003-07-18 00:00:00
2005-07-18 00:00:00
2013-08-18 00:00:00
2013-08-18 00:00:00
2013-08-18 00:00:00
2018-06-20 00:00:00
2020-08-18 00:00:00
2022-08-18 00:00:00
2022-08-18 00:00:00
2023-08-18 00:00:00
2031-08-18 00:00:00
2007-09-18 00:00:00
2014-09-18 00:00:00
2018-09-18 00:00:00
2019-09-18 00:00:00
2019-09-18 00:00:00
2027-09-18 00:00:00
2002-10-18 00:00:00
2005-10-18 00:00:00
2016-10-18 00:00:00
2017-10-18 00:00:00
2018-10-18 00:00:00
2022-10-18 00:00:00
2025-10-18 00:00:00
2027-10-18 00:00:00
2030-10-18 00:00:00
2031-10-18 00:00:00
2007-11-18 00:00:00
2007-11-18 00:00:00
2007-11-18 00:00:00
2008-11-18 00:00:00
2008-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2012-11-18 00:00:00
2014-11-18 00:00:00
2014-11-18 00:00:00
2014-11-18 00:00:00
2016-11-18 00:00:00
2016-11-18 00:00:00
2016-11-18 00:00:00
2028-11-18 00:00:00
2028-11-18 00:00:00
2028-11-18 00:00:00
2006-12-18 00:00:00
2006-12-18 00:00:00
2005-11-19 00:00:00
2013-12-18 00:00:00
2015-12-18 00:00:00
2015-12-18 00:00:00
2015-12-18 00:00:00
2015-12-18 00:00:00
2015-12-18 00:00:00
2017-12-18 00:00:00
2017-12-18 00:00:00
2020-12-18 00:00:00
2020-12-18 00:00:00
2021-12-18 00:00:00
2021-12-18 00:00:00
2024-12-18 00:00:00
2024-12-18 00:00:00
2024-12-18 00:00:00
2027-12-18 00:00:00
2031-12-18 00:00:00
2005-01-19 00:00:00
2015-01-19 00:00:00
2015-01-19 00:00:00
2015-01-19 00:00:00
2015-01-19 00:00:00
2016-01-19 00:00:00
2017-01-19 00:00:00
2017-01-19 00:00:00
2017-01-19 00:00:00
2021-01-19 00:00:00
2023-01-19 00:00:00
2029-01-19 00:00:00
2029-01-19 00:00:00
2029-01-19 00:00:00
2029-01-19 00:00:00
2031-01-19 00:00:00
2001-02-19 00:00:00
2001-02-19 00:00:00
2007-02-19 00:00:00
2007-02-19 00:00:00
2008-02-19 00:00:00
2008-02-19 00:00:00
2016-06-20 00:00:00
2020-06-20 00:00:00
2012-02-19 00:00:00
2012-02-19 00:00:00
2012-02-19 00:00:00
2013-02-19 00:00:00
2013-02-19 00:00:00
2014-02-19 00:00:00
2016-06-20 00:00:00
2015-02-19 00:00:00
2015-02-19 00:00:00
2015-02-19 00:00:00
2019-02-19 00:00:00
2018-06-20 00:00:00
2020-02-19 00:00:00
2021-02-19 00:00:00
2021-02-19 00:00:00
2021-02-19 00:00:00
2022-02-19 00:00:00
2023-02-19 00:00:00
2025-02-19 00:00:00
2025-02-19 00:00:00
2025-02-19 00:00:00
2025-02-19 00:00:00
2026-02-19 00:00:00
2026-02-19 00:00:00
2026-02-19 00:00:00
2026-02-19 00:00:00
2028-02-19 00:00:00
2028-02-19 00:00:00
2028-02-19 00:00:00
2028-02-19 00:00:00
2028-02-19 00:00:00
2028-02-19 00:00:00
2004-03-19 00:00:00
2005-03-19 00:00:00
2005-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2007-03-19 00:00:00
2017-06-20 00:00:00
2017-06-20 00:00:00
2012-03-19 00:00:00
2013-03-19 00:00:00
2014-03-19 00:00:00
2014-03-19 00:00:00
2016-03-19 00:00:00
2016-03-19 00:00:00
2018-03-19 00:00:00
2019-03-19 00:00:00
2019-03-19 00:00:00
2019-03-19 00:00:00
2019-03-19 00:00:00
2020-03-19 00:00:00
2020-03-19 00:00:00
2020-05-20 00:00:00
2022-03-19 00:00:00
2025-03-19 00:00:00
2022-06-20 00:00:00
2025-03-19 00:00:00
2025-03-19 00:00:00
2025-03-19 00:00:00
2025-03-19 00:00:00
2025-03-19 00:00:00
2026-03-19 00:00:00
2026-03-19 00:00:00
2026-03-19 00:00:00
2015-06-20 00:00:00
2027-03-19 00:00:00
2027-03-19 00:00:00
2018-06-20 00:00:00
2029-03-19 00:00:00
2030-03-19 00:00:00
2030-03-19 00:00:00
2030-03-19 00:00:00
2030-03-19 00:00:00
2001-04-19 00:00:00
2001-04-19 00:00:00
2001-04-19 00:00:00
2015-06-20 00:00:00
2001-04-19 00:00:00
2001-04-19 00:00:00
2018-06-20 00:00:00
2018-06-20 00:00:00
2003-04-19 00:00:00
2003-04-19 00:00:00
2004-04-19 00:00:00
2008-04-19 00:00:00
2008-04-19 00:00:00
2022-06-20 00:00:00
2011-04-19 00:00:00
2012-04-19 00:00:00
2012-04-19 00:00:00
2012-04-19 00:00:00
2012-04-19 00:00:00
2015-04-19 00:00:00
2017-04-19 00:00:00
2018-04-19 00:00:00
2022-06-20 00:00:00
2019-04-19 00:00:00
2019-04-19 00:00:00
2019-04-19 00:00:00
2019-04-19 00:00:00
2019-04-19 00:00:00
2019-04-19 00:00:00
2019-04-19 00:00:00
2019-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2023-04-19 00:00:00
2024-04-19 00:00:00
2025-04-19 00:00:00
2026-04-19 00:00:00
2026-04-19 00:00:00
2017-06-20 00:00:00
2017-06-20 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2029-04-19 00:00:00
2030-04-19 00:00:00
2030-04-19 00:00:00
2017-06-20 00:00:00
2030-04-19 00:00:00
2017-06-20 00:00:00
2030-04-19 00:00:00
2017-06-20 00:00:00
2030-04-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2002-05-19 00:00:00
2008-05-19 00:00:00
2008-05-19 00:00:00
2008-05-19 00:00:00
2009-05-19 00:00:00
2009-05-19 00:00:00
2009-05-19 00:00:00
2010-05-19 00:00:00
2010-05-19 00:00:00
2010-05-19 00:00:00
2010-05-19 00:00:00
2011-05-19 00:00:00
2011-05-19 00:00:00
2013-05-19 00:00:00
2013-05-19 00:00:00
2013-05-19 00:00:00
2013-05-19 00:00:00
2013-05-19 00:00:00
2013-05-19 00:00:00
2014-05-19 00:00:00
2014-05-19 00:00:00
2016-05-19 00:00:00
2019-06-20 00:00:00
2017-05-19 00:00:00
2017-05-19 00:00:00
2019-05-19 00:00:00
2019-05-19 00:00:00
2019-05-19 00:00:00
2019-06-20 00:00:00
2023-05-19 00:00:00
2023-05-19 00:00:00
2023-05-19 00:00:00
2023-05-19 00:00:00
2023-05-19 00:00:00
2023-05-19 00:00:00
2023-05-19 00:00:00
2024-05-19 00:00:00
2028-05-19 00:00:00
2028-05-19 00:00:00
2028-05-19 00:00:00
2028-05-19 00:00:00
2030-05-19 00:00:00
2030-05-19 00:00:00
2031-05-19 00:00:00
2026-07-19 00:00:00
2031-05-19 00:00:00
2031-05-19 00:00:00
2031-05-19 00:00:00
2031-05-19 00:00:00
2031-05-19 00:00:00
2031-05-19 00:00:00
2031-05-19 00:00:00
2003-06-19 00:00:00
2003-06-19 00:00:00
2003-06-19 00:00:00
2003-06-19 00:00:00
2003-06-19 00:00:00
2003-06-19 00:00:00
2004-06-19 00:00:00
2012-06-20 00:00:00
2004-06-19 00:00:00
2004-06-19 00:00:00
2005-06-19 00:00:00
2005-06-19 00:00:00
2005-06-19 00:00:00
2005-06-19 00:00:00
2005-06-19 00:00:00
2007-06-19 00:00:00
2007-06-19 00:00:00
2007-06-19 00:00:00
2010-06-19 00:00:00
2019-06-20 00:00:00
2001-06-20 00:00:00
2012-06-19 00:00:00
2020-06-20 00:00:00
2012-06-19 00:00:00
2012-06-19 00:00:00
2020-06-20 00:00:00
2012-06-19 00:00:00
2013-06-19 00:00:00
2013-06-19 00:00:00
2013-06-19 00:00:00
2013-06-19 00:00:00
2014-06-19 00:00:00
2014-06-19 00:00:00
2017-06-19 00:00:00
2018-06-19 00:00:00
2018-06-19 00:00:00
2018-06-19 00:00:00
2018-06-19 00:00:00
2018-06-19 00:00:00
2018-06-19 00:00:00
2018-06-19 00:00:00
2019-06-19 00:00:00
2016-07-19 00:00:00
2020-06-19 00:00:00
2018-06-20 00:00:00
2024-06-19 00:00:00
2024-06-19 00:00:00
2024-06-19 00:00:00
2024-06-19 00:00:00
2024-06-19 00:00:00
2024-06-19 00:00:00
2024-06-19 00:00:00
2024-06-19 00:00:00
2027-06-19 00:00:00
2027-06-19 00:00:00
2027-06-19 00:00:00
2012-08-19 00:00:00
2018-06-20 00:00:00
2002-07-19 00:00:00
2002-07-19 00:00:00
2002-07-19 00:00:00
2002-07-19 00:00:00
2002-07-19 00:00:00
2008-06-20 00:00:00
2008-06-20 00:00:00
2016-06-20 00:00:00
2003-07-19 00:00:00
2003-07-19 00:00:00
2004-07-19 00:00:00
2004-07-19 00:00:00
2004-07-19 00:00:00
2008-07-19 00:00:00
2008-07-19 00:00:00
2008-07-19 00:00:00
2012-08-19 00:00:00
2012-08-19 00:00:00
2009-07-19 00:00:00
2009-07-19 00:00:00
2010-07-19 00:00:00
2011-07-19 00:00:00
2011-07-19 00:00:00
2011-07-19 00:00:00
2012-07-19 00:00:00
2012-07-19 00:00:00
2015-07-19 00:00:00
2015-07-19 00:00:00
2015-07-19 00:00:00
2015-07-19 00:00:00
2015-07-19 00:00:00
2018-07-19 00:00:00
2018-07-19 00:00:00
2018-07-19 00:00:00
2018-07-19 00:00:00
2019-07-19 00:00:00
2019-07-19 00:00:00
2019-07-19 00:00:00
2020-07-19 00:00:00
2020-07-19 00:00:00
2020-07-19 00:00:00
2020-07-19 00:00:00

2020-07-19 00:00:00
2020-07-19 00:00:00
2020-07-19 00:00:00
2020-07-19 00:00:00
2022-07-19 00:00:00
2022-07-19 00:00:00
2023-07-19 00:00:00
2023-07-19 00:00:00
2023-07-19 00:00:00
2023-07-19 00:00:00
2024-07-19 00:00:00
2024-07-19 00:00:00
2024-07-19 00:00:00
2024-07-19 00:00:00
2025-07-19 00:00:00
2022-06-20 00:00:00
2029-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2030-07-19 00:00:00
2001-08-19 00:00:00
2001-08-19 00:00:00
2001-08-19 00:00:00
2001-08-19 00:00:00
2002-08-19 00:00:00
2002-08-19 00:00:00
2002-08-19 00:00:00
2002-08-19 00:00:00
2002-08-19 00:00:00
2005-08-19 00:00:00
2005-08-19 00:00:00
2005-08-19 00:00:00
2006-08-19 00:00:00
2007-08-19 00:00:00
2007-08-19 00:00:00
2022-06-20 00:00:00
2007-08-19 00:00:00
2007-08-19 00:00:00
2007-08-19 00:00:00
2008-08-19 00:00:00
2009-08-19 00:00:00
2009-08-19 00:00:00
2009-08-19 00:00:00
2013-08-19 00:00:00
2014-08-19 00:00:00
2014-08-19 00:00:00
2014-08-19 00:00:00
2014-08-19 00:00:00
2014-08-19 00:00:00
2017-06-20 00:00:00
2016-08-19 00:00:00
2016-08-19 00:00:00
2019-08-19 00:00:00
2019-08-19 00:00:00
2019-08-19 00:00:00
2019-08-19 00:00:00
2019-08-19 00:00:00
2015-06-20 00:00:00
2020-08-19 00:00:00
2020-08-19 00:00:00
2020-08-19 00:00:00
2020-08-19 00:00:00
2021-08-19 00:00:00
2021-08-19 00:00:00
2021-08-19 00:00:00
2021-08-19 00:00:00
2021-08-19 00:00:00
2022-08-19 00:00:00
2023-08-19 00:00:00
2023-08-19 00:00:00
2023-08-19 00:00:00
2023-08-19 00:00:00
2023-08-19 00:00:00
2023-08-19 00:00:00
2023-08-19 00:00:00
2026-08-19 00:00:00
2027-08-19 00:00:00
2027-08-19 00:00:00
2027-08-19 00:00:00
2027-08-19 00:00:00
2027-08-19 00:00:00
2028-08-19 00:00:00
2028-08-19 00:00:00
2028-08-19 00:00:00
2028-08-19 00:00:00
2028-08-19 00:00:00
2028-08-19 00:00:00
2028-08-19 00:00:00
2029-08-19 00:00:00
2029-08-19 00:00:00
2029-08-19 00:00:00
2029-08-19 00:00:00
2029-08-19 00:00:00
2030-08-19 00:00:00
2017-06-20 00:00:00
2030-08-19 00:00:00
2030-08-19 00:00:00
2030-08-19 00:00:00
2030-08-19 00:00:00
2030-08-19 00:00:00
2002-09-19 00:00:00
2002-09-19 00:00:00
2002-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2003-09-19 00:00:00
2004-09-19 00:00:00
2004-09-19 00:00:00
2004-09-19 00:00:00
2004-09-19 00:00:00
2005-09-19 00:00:00
2005-09-19 00:00:00
2005-09-19 00:00:00
2005-09-19 00:00:00
2005-09-19 00:00:00
2005-09-19 00:00:00
2005-09-19 00:00:00
2006-09-19 00:00:00
2006-09-19 00:00:00
2006-09-19 00:00:00
2009-09-19 00:00:00
2016-06-20 00:00:00
2016-06-20 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2009-09-19 00:00:00
2017-06-20 00:00:00
2010-09-19 00:00:00
2010-09-19 00:00:00
2010-09-19 00:00:00
2010-09-19 00:00:00
2017-06-20 00:00:00
2022-06-20 00:00:00
2022-06-20 00:00:00
2011-09-19 00:00:00
2016-09-19 00:00:00
2016-09-19 00:00:00
2016-09-19 00:00:00
2016-09-19 00:00:00
2016-09-19 00:00:00
2016-09-19 00:00:00
2017-09-19 00:00:00
2017-09-19 00:00:00
2017-09-19 00:00:00
2017-09-19 00:00:00
2017-09-19 00:00:00
2017-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2018-09-19 00:00:00
2019-09-19 00:00:00
2020-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00
2023-09-19 00:00:00

In [104]:
pna_data_sample

,CUST_ORDR_NO,ORDR_TYPE_ID,MAX(POD.PROD_ID),MAX(POD.FIRST_CRET_DT),MAX(POD.LAST_CHG_DT),MAX(POD.CUST_ORDR_VER_NO),ORRE,PRDI,LORD,PHRD,RECO,WODI,REAC,JUJO,SWBO,FUCO,MAUP,ORCN,dates
0,12004B404235891,PE,0501,17/12/23,20/06/22,1,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,1_PHRD_2_OKEY,NaN,NaN,1_REAC_2_OKEY,NaN,NaN,NaN,1_MAUP_7_OKEY,1_ORCN_7_OKEY,2023-12-17 00:00:00
1,13031C1154544B0,VE,0701,20/06/18,20/06/18,44,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,NaN,NaN,1_WODI_6_OKEY,1_REAC_2_OKEY,NaN,NaN,1_FUCO_0_OKEY,NaN,NaN,2018-06-20 00:00:00
2,14056F013823791,B1,0501,14/06/12,20/06/17,5,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,1_PHRD_2_OKEY,1_RECO_0_OKEY,1_WODI_5_OKEY,NaN,NaN,NaN,NaN,NaN,NaN,2012-06-14 00:00:00
3,14065F251372990,OA,0822,14/06/11,20/06/22,3,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,1_PHRD_2_OKEY,1_RECO_7_OKEY,1_WODI_7_OKEY,NaN,NaN,NaN,NaN,1_MAUP_7_OKEY,1_ORCN_2_OKEY,2011-06-14 00:00:00
4,14114H2241900A0,VA,070M,20/06/15,20/06/15,3,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-06-20 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,19266AO00900191,B1,0503,19/09/23,20/06/22,1,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1_MAUP_2_OKEY,1_ORCN_2_OKEY,2023-09-19 00:00:00
996,19266AO00900291,B1,0503,19/09/23,20/06/22,1,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1_MAUP_2_OKEY,1_ORCN_2_OKEY,2023-09-19 00:00:00
997,19266AO00900391,B1,0503,19/09/23,20/06/22,1,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1_MAUP_2_OKEY,1_ORCN_2_OKEY,2023-09-19 00:00:00
998,19266AO00900491,B1,0503,19/09/23,20/06/22,1,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1_MAUP_2_OKEY,1_ORCN_2_OKEY,2023-09-19 00:00:00
999,19266AO00900591,B1,0503,19/09/23,20/06/22,1,1_ORRE_2_OKEY,1_PRDI_2_OKEY,1_LORD_2_OKEY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1_MAUP_2_OKEY,1_ORCN_2_OKEY,2023-09-19 00:00:00